version: '3.8'

services:
  enigma-prod:
    container_name: enigma-prod-container
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_SECURE}:443