name: Test build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - uses: action/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - run: npm install yarn
      - run: yarn install
      - run: yarn build